name: Update Data

on:
  schedule:
    - cron: '0 * * * *' #Every hour 
  workflow_dispatch:  # Manually

permissions:
  contents: write  # Esto permite al bot hacer push al repositorio

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Set up git to push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{secrets.PAT}}@github.com/StipGod/mlops-ebernalc-jjsanchezc
 
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.20' 
      
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          cd lab2
          pip install -r requirements.txt
          
      - name: Execute python script 
        run: |
            cd lab2
            cd data_extraction
            pwd
            python extract_data.py

      - name: Update Data
        run: |
          cd lab2
          cd data_extraction
          pwd
          bash ./update_data.sh 